"""Initial Migration

Revision ID: 216e88587a41
Revises: eea8c05d0a02
Create Date: 2022-05-08 16:12:34.458414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216e88587a41'
down_revision = 'eea8c05d0a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('pitches', sa.Column('post', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'post')
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###
