"""Initial Migration

Revision ID: 76341626f8c9
Revises: 4edfabd4a069
Create Date: 2022-05-08 22:30:32.131275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76341626f8c9'
down_revision = '4edfabd4a069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'time')
    # ### end Alembic commands ###
