"""Initial Migration

Revision ID: 8e3ee1912318
Revises: 8f0fc1447c5a
Create Date: 2022-05-09 11:27:48.654062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3ee1912318'
down_revision = '8f0fc1447c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secure_password_', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'secure_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secure_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'secure_password_')
    # ### end Alembic commands ###
